services:
  host-client:
    image: pico/host:0.0.1
    build: ./host
    restart: always
    container_name: host-client 
    environment:
      - TEXT_SERVER_IP=device1
      - TEXT_SERVER_PORT=2004
    stdin_open: true
    tty: true
    #command: python /app/client.py
    command: /bin/bash
  host-server:
    image: pico/host:0.0.1
    restart: always
    container_name: host-server 
    environment:
      - TEXT_SERVER_IP=device2
      - TEXT_SERVER_PORT=2004
    stdin_open: true
    tty: true
    command: python /app/server.py
  device1:
    image: pico/async-device:0.0.1
    build: ./async-device
    restart: always
    container_name: pico-01
    environment:
      - HOST_IP=host-client
      - HOST_PORT=2004
      - PEER_IP=device2
      - PEER_PORT=8503
    stdin_open: true
    tty: true
  device2:
    image: pico/async-device:0.0.1
    restart: always
    container_name: pico-02
    environment:
      - HOST_IP=host-server
      - HOST_PORT=2004
      - PEER_IP=device1
      - PEER_PORT=8503
    stdin_open: true
    tty: true